### ISSUE TITLE
Setup Ubuntu template missing some ami id's for some regions (Tokyo, etc.)

### ISSUE THREAD

**Issue by tkam8** [f5devcentral/f5-big-iq-trial#2]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

(https://s3.amazonaws.com/big-iq-quickstart-cf-templates/6.0.0/Setup-Ubuntu-Trial.template)

##### SUMMARY

When trying to launch the CFT in the tokyo region (ap-northeast-1), stack launch fails because unable to map to a tokyo region ami id for ubuntu. This isn't listed in the CFT for Setup-Ubuntu-Trial.template. 

"Unable to get mapping for AWSRegionArch2AMI::ap-northeast-1::64"

Tokyo Region ubuntu 16.0.4:
Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-940cdceb

##### STEPS TO REPRODUCE

1. Click Launch button here: https://github.com/f5devcentral/f5-big-ip-cloud-edition-trial-quick-start
2. Attempt to launch in Tokyo region
3. confirm failure in events. 

##### WORKAROUND ATTEMPTED

1. Download both nested template "Setup-Ubuntu-Trial.template" and the "bigiq-cm-dcd-pair-with-ssg.template"
2. Modify the "Setup-Ubuntu-Trial.template" with the ami id for Ubuntu in tokyo region
3. UPload the modified "Setup-Ubuntu-Trial.template" to S3 and make read only
4. Modify "bigiq-cm-dcd-pair-with-ssg.template" to point to the location of the modified "Setup-Ubuntu-Trial.template"
5. Upload stack to AWS and launch

##### EXPECTED RESULTS

CFT to deploy in Tokyo region

##### ACTUAL RESULTS
Failed to launch stack

```
Template error: Unable to get mapping for AWSRegionArch2AMI::ap-northeast-1::64
```
![image](https://user-images.githubusercontent.com/19481266/44244957-82f46a80-a211-11e8-97e7-0cbdb089c79a.png)

**Comment by rjouhann** [comment]
Fixed in new branch 6.0.1
