### ISSUE TITLE
Issue when I was creating one more application after created a new ELB on AWS

### ISSUE THREAD

**Issue by a4n0nym0u5** [f5devcentral/f5-big-iq-trial#3]
Hi,

I have deployed the infrasturcture by following your template successfully. However, after I tried to create one more Elastic load balancer on AWS and create a new application on the BIGIQ CE, it prompt out an error and said " there is an error during the deployment ".

Let say, if I would like to deploy one more application on BIGIQ CE and use the WAF per App VE license.
Other than creating the Service Scaling group again and make use of the AWS default https WAF template, any other important configuration did I miss which cause an error ?

**Comment by rjouhann** [comment]
Hello,

The PerApp VE trial license only offer 3 virtual servers. The application deployed with this trial consumes 2 virtual servers (listening on port 443 and 80 for the HTTP redirect). If you want to deploy another application using the same Service Scaling Group, you will need to either use a different license (contact F5), or deploy your 2nd app on a new Service Scaling Group (be careful, the trial license gives you max 3 BIG-IP VEs).

Note: Each application you deploy requires its own, dedicated resources. For each application you need:
- a unique ELB.
- a security group associated with that ELB.
- a virtual server port.
For example: you could configure two applications on the same SSG, but you would need two ELBs, each with its own security group. You could use Load Balancer Port 80 for both ELBs, but the Instance Port on one ELB could use 1000 and the second application could use 2000.

[More details in the documentation](https://support.f5.com/kb/en-us/products/big-iq-centralized-mgmt/manuals/product/big-iq-centralized-management-auto-scaling-in-aws-6-0-1/07.html)
