### ISSUE TITLE
Deploying per app VE (LTM module)

### ISSUE THREAD

**Issue by a4n0nym0u5** [f5devcentral/f5-big-iq-trial#4]
If I would like to deploy the per app ve (LTM module) instead of WAF module for cloud edition on the AWS environment, which template should I select? Is there any concern regarding to the configuration comparing with WAF? Or more or less the same

Thank you.

**Comment by rjouhann** [comment]
This trial quick start is deploying a WAF and the BIG-IP is provisioned differently.
If you want to test the PerApp VE LTM module only (no WAF), you could:

1. Launch the quick start
2. Remove the demo app service WAF if any (Applications tab, APPLICATIONS > Delete)
3. Delete the existing WAF SSG (Applications tab, ENVIRONMENTS > Service Scaling Groups > Delete)
4. Setup another license pool using the LTM trial license (Devices tab, LICENSE MANAGEMENT > Licenses > Add RegKey Pool)
5. Update the Service to deploy and the BIG-IQ License Pool Name  (Applications > ENVIRONMENTS > Cloud Environments)

![image](https://user-images.githubusercontent.com/25542366/45522347-4f0c5680-b777-11e8-83b8-92a26abb708a.png)

![image](https://user-images.githubusercontent.com/25542366/45522441-f12c3e80-b777-11e8-95c0-22d1816d6b07.png)

6. Create your LTM SSG (Applications tab, ENVIRONMENTS > Service Scaling Groups > Create)
7. Create your demo app service LTM (Applications tab, APPLICATIONS > Create)

More information/details in our [knowledge center](https://support.f5.com/kb/en-us/products/big-iq-centralized-mgmt/manuals/product/big-iq-centralized-management-auto-scaling-in-aws-6-0-1.html).

**Comment by a4n0nym0u5** [comment]
Thanks for your reply. However, I have encountered an issue during app. deployment ( I have created a new ELB, scaling group and new environment) , it prompts out "Error encountered during deployment" , I have selected "Default-AWS-f5-HTTPS-offload-lb-template" and the ELB has configured for TCP 80 and TCP 443.

So, do you have any idea? Thanks.

**Comment by rjouhann** [comment]
Before deploying the app service, make sure the ELB has no listeners configured already.

![image](https://user-images.githubusercontent.com/25542366/45556418-1066b280-b7f0-11e8-9d55-8c6ffe75400e.png)

**Comment by a4n0nym0u5** [comment]
I have tried the procedure from the document and above, but still it shown 'Error encountered during deployment.'
May I ask have you try to deploy the LTM module for Cloud Edition before? Thanks

**Comment by rjouhann** [comment]
Yes, it works with LTM module. I believe something else is wrong in your configuration. Could you reach to a [local F5 sales engineer](https://www.f5.com/products/get-f5#contactsales) to help you out? I don't think we will resolve this over github.
