### ISSUE TITLE
doc correction from aws to azure for catalogue selection

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-big-iq-trial#6]
I was reading the Azure quick start and noticed a reference to AWS templates for the service catalogue item. Is this right?

https://github.com/f5devcentral/f5-big-ip-cloud-edition-trial-quick-start/tree/6.1.0/azure

--snippet (scroll down)
Click the Applications tab > APPLICATIONS. Create. Select Default-AWS-f5-HTTPS-WAF-lb-template

Are there supposed to be Azure templates referenced?

**Comment by rjouhann** [comment]
Hello Jeff,
The template for AWS works as well with Azure. 
Thanks
