### ISSUE TITLE
AWS quick start creates AWS "cloud environment" without selecting AMI image

### ISSUE THREAD

**Issue by JeffGiroux** [f5devcentral/f5-big-iq-trial#7]
The AWS quick start will deploy the BIG-IQ and DCD successfully. But, the SSG fails. When I look at "Cloud Environment" section, the AMI Image type is blank. Meaning, the dropdown is still on "Select" which means no image is selected. As a result, it looks like the latest AMI is referenced in AWS which is currently ami-04e893bab1e8b9b10. This is running 14.0. Something with this image and/or version 14.0 breaks the SSG deployment. 

As a fix, I created a new cloud environment and this time I made sure AMI had an image selected. I chose the 13.1.1 Best 1 boot slot. For reference, that ends up being image ami-58c3d327. This works successfully, and the SSG deployed correctly and shows an active state. This proves the entire deployment eventually works great.

Something is wrong in the auto-creation scripts for the cloud environment. It needs to have an AMI type selected. Otherwise it defaults to 14.0 and it breaks. If that's the goal, then something in 14.0 and BIG-IQ needs to be fixed.

**Comment by JeffGiroux** [comment]
For reference...
1. Login to BIG-IQ
2. Go to Application tab
3. Click on "Cloud Environments"
4. View properties for aws-env
5. Notice AMI type is blank

**Comment by rjouhann** [comment]
Replaced 14.0 BIG-IP AMI with 13.1.1 BIG-IP AMI.
